In [622]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from copy import deepcopy
%matplotlib inline 

In [632]:
group1 = {
    "infinitive": ["bend", "build","lend", "send", "spend", "geld", "gild", "gird", "rend", "shend" ], 
    "past": ["bent", "built", "lent", "sent", "spend", "gelt", "gilt", "girt", "rent", "shent" ], 
    "label": [1] * 10,
    "description": ["d->t"] * 10
}

In [633]:
group1

{'description': ['d->t',
  'd->t',
  'd->t',
  'd->t',
  'd->t',
  'd->t',
  'd->t',
  'd->t',
  'd->t',
  'd->t'],
 'infinitive': ['bend',
  'build',
  'lend',
  'send',
  'spend',
  'geld',
  'gild',
  'gird',
  'rend',
  'shend'],
 'label': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 'past': ['bent',
  'built',
  'lent',
  'sent',
  'spend',
  'gelt',
  'gilt',
  'girt',
  'rent',
  'shent']}

In [634]:
g1 = pd.DataFrame(group1)

In [635]:
group2 = { "infinitive":["lay", "pay", "say"], 
           "past":["laid", "paid", "said"], 
           "label": [2] * 3, 
           "description": "ay -> aid"
    
}

In [636]:
g2 = pd.DataFrame(group2)

In [637]:
group3 = {
    "infinitive": ["creep",  "feed", "feel", "keep",  "meet", "sleep", "sweep", "weep", "breed"],
    "past": ["crept",  "fed", "felt", "kept", "met", "slept", "swept", "wept", "bred" ], 
    "label" : [3] * 9, 
    "description": ["d or t ending"] * 9
}

In [638]:
g3 = pd.DataFrame(group3)

In [639]:
group4 = {
    "infinitive": ["bet", "bid", "cost", "cut", "fit", "spit", "split", "set", "hurt", "shut", "put"], 
    "past":["bet", "bid", "cost", "cut", "fit", "spit", "split", "set", "hurt", "shut", "put"], 
    "label": [4] * 11, 
    "description":["d or t ending: do not change"] * 11
}

In [640]:
g4 = pd.DataFrame(group4)

In [641]:
group5 = {
    "infinitive": ["break", "speak", "steal", "weave", "choose", "freeze", "awake", "wake", "reeve"], 
    "past": ["broke", "spoke", "stole", "wove", "chose", "froze", "awoke", "woke", "rove"], 
    "label": [5] * 9, 
    "description": ["vowel change: ending with e"] * 9
    
}

In [642]:
g5 = pd.DataFrame(group5)

In [643]:
group6 = {
    "infinitive": ["arise", "rise", "ride", "drive", "write", "shine", "abide", "dive", "strive", "stride" ], 
    "past": ["arose", "rose", "rode", "drove", "wrote", "shone", "abode", "dove", "strove", "strode"], 
    "label": [6] * 10, 
    "description": ["change i > o"] * 10
}

In [644]:
g6 = pd.DataFrame(group6)

In [645]:
group7 = {
    "infinitive":["bear", "swear","tear", "wear"], 
    "past": ["bore", "swore", "tore", "wore"], 
    "label": [7] * 4, 
    "description":["ear -> ore"] * 4
}

In [646]:
g7 = pd.DataFrame(group7)

In [647]:
group8 = {
    "infinitive": ["blow", "grow", "know", "throw"], 
    "past": ["blew", "grew", "knew", "threw"], 
    "label": [8] * 4, 
    "description": ["ow > ew"] * 4
}

In [648]:
g8 = pd.DataFrame(group8) 

In [649]:
group9 = {
    "infinitive": ["stick", "sting", "swing", "hang" ], 
    "past": ["stuck", "stung", "swung", "hung"], 
    "label": [9] * 4, 
    "description": ["i > u"] * 4
}

In [650]:
g9 = pd.DataFrame(group9)

In [651]:
group10 = {
    "infinitive": ["bind", "find", "grind", "wind"], 
    "past": ["bound", "found", "ground", "wound"], 
    "label":[10]* 4, 
    "description":["i > ou"] * 4
}

In [652]:
g10 = pd.DataFrame(group10)

In [653]:
group11 = {
    "infinitive": ["answer", "attempt", "boil", "calculate", "collect", "command", "depend"], 
    "past":["answered", "attepted", "boiled", "calculated", "collected", "commanded", "depended"], 
    "label": [11] * 7, 
    "description": ["add ed"] * 7
}
g11 = pd.DataFrame(group11)

In [654]:
data = pd.concat([g1, g2, g3, g4, g5, g6, g7, g8, g9,g10, g11], axis = 0)

In [669]:
cked = pd.read_csv("cked.csv")
ed = pd.read_csv("e_d.csv")
ied = pd.read_csv("ied.csv")

In [671]:
ied.drop(ied.columns[[0,3]], axis = 1, inplace = True)

In [672]:
ed.drop(ed.columns[[0,3]], axis = 1, inplace = True)

In [673]:
cked.drop(cked.columns[[0,3]], axis = 1, inplace = True)

In [677]:
ied["label"] = 12
ed["label"] = 13
cked["label"] = 14

In [678]:
ied["description"] = "y > i: add ed"
ed["description"] = "add d"
cked["description"] = "add k and ed"

In [697]:
data = pd.concat([data, cked])

In [700]:
data.to_csv("data_final.csv")

In [699]:
data.label.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 12, 14], dtype=int64)

In [375]:
features = ["a", "e", "i", "o", "u", "last_letter"]

In [376]:
last_letters = data.infinitive.str[-1:]
last_letters.name = "last_letter"

In [377]:
a = data.infinitive.str.count("a")
a.name = "a"

In [378]:
e = data.infinitive.str.count("e")
e.name = "e"

In [379]:
i = data.infinitive.str.count("i")
i.name = "i"

In [380]:
o = data.infinitive.str.count("o")
o.name = "o"

In [381]:
u = data.infinitive.str.count("u")
u.name = "u"

In [382]:
data_df = pd.concat([a,e,i,o,u, last_letters, data.label], axis = 1)

In [383]:
data_df.shape

(58, 7)

In [384]:
labels = data.label.unique()

In [385]:
data_df.index = np.arange(data_df.shape[0])
data_df.index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57],
           dtype='int64')

In [386]:
validation = pd.DataFrame(columns = data_df.columns)

    

In [387]:
data_df[data_df.label == 1].sample(replace = False, n = 1)

a  e  i  o  u last_letter  label
0  0  1  0  0  0           d      1

In [388]:
for label in labels:
    df = data_df[data_df.label == label].sample()
    validation = pd.concat([validation, df], axis = 0)

In [389]:
data_df[~data_df.index.isin(validation.index)].shape

(47, 7)

In [425]:
def validation_set(data):
    labels = data.label.unique()
    validation = pd.DataFrame(columns = data.columns)    
    for label in labels:
        df = data[data.label == label].sample()
        validation = pd.concat([validation, df], axis = 0)
    train = data_df[~data_df.index.isin(validation.index)]
    return train, validation
    
    

In [431]:
train, valid = validation_set(data_df)

valid.columns

Index([u'a', u'e', u'i', u'o', u'u', u'last_letter', u'label'], dtype='object')

In [433]:
from sklearn.linear_model import LogisticRegression
data_df.label.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [438]:
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le = preprocessing.LabelEncoder()

In [460]:
models = {}
predictions = {}
df_tmp, valid = validation_set(data_df)
le.fit(df_tmp.last_letter)
df_tmp["lletter"] = le.transform(df_tmp.last_letter)

C:\Users\Lenovo\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [494]:
df_tmp.label.unique()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [463]:
df_tmp = df_tmp[df_tmp.columns.difference(["last_letter"])]


In [464]:
valid["lletter"] = le.transform(valid["last_letter"])

In [465]:
valid = valid[valid.columns.difference(["last_letter"])]


In [523]:
X = df_tmp[df_tmp.columns.difference(["label"])]
y = df_tmp["label"]
X.columns

Index([u'a', u'e', u'i', u'lletter', u'o', u'u'], dtype='object')

In [540]:
X[y == 1]

a  e  i  lletter  o  u
0  0  1  0        0  0  0
2  0  1  0        0  0  0
3  0  1  0        0  0  0
4  0  1  0        0  0  0

In [547]:
for label in labels:       
    y_train = pd.Series(np.where(y == label, 1, 0))
    print y_train.nunique()
    model  = RandomForestClassifier( random_state=0)
    model.fit(X= X, y= y_train)
    models[label] = model
 
    
   
    

2
2
2
2
2
2
2
2
2
2
2


In [602]:
l = []
for label in labels:
    m1 = models[label]
    y_preds = m1.predict_proba(X_test)
    s = pd.Series(y_preds[:, 1])
    l.append(s)

In [619]:
pd.concat(l, axis = 1).idxmax(axis = 1)

0     9
1     1
2     2
3     3
4     4
5     5
6     6
7     7
8     8
9     9
10    3
dtype: int64

In [543]:
X_test = valid[valid.columns.difference(["label"])]
y_test = valid["label"]

In [545]:
model = models[1]
y_preds = model1.predict_proba(X_test)
y_preds.shape

(11L, 11L)

array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3], dtype=int64)

In [522]:
df_tmp.label.value_counts()

5     7
3     7
11    6
6     5
4     4
1     4
10    3
9     3
8     3
7     3
2     2
Name: label, dtype: int64

In [396]:
neg = data_df[~data_df.index.isin(idx)].index

In [397]:
tmp.loc[neg, "label"] = 0

In [402]:
deepcopy(data_df)

a  e  i  o  u last_letter  label
0   0  1  0  0  0           d      1
1   0  0  1  0  1           d      1
2   0  1  0  0  0           d      1
3   0  1  0  0  0           d      1
4   0  1  0  0  0           d      1
5   1  0  0  0  0           y      2
6   1  0  0  0  0           y      2
7   1  0  0  0  0           y      2
8   0  2  0  0  0           p      3
9   0  2  0  0  0           d      3
10  0  2  0  0  0           l      3
11  0  2  0  0  0           p      3
12  0  2  0  0  0           t      3
13  0  2  0  0  0           p      3
14  0  2  0  0  0           p      3
15  0  2  0  0  0           p      3
16  0  1  0  0  0           t      4
17  0  0  1  0  0           d      4
18  0  0  0  1  0           t      4
19  0  0  0  0  1           t      4
20  0  0  1  0  0           t      4
21  1  1  0  0  0           k      5
22  1  1  0  0  0           k      5
23  1  1  0  0  0           l      5
24  1  2  0  0  0           e      5
25  0  1  0  2  0           e      5
26  0  3  0  0  0           e      5
27  2  1  0  0  0           e      5
28  1  1  0  0  0           e      5
29  1  1  1  0  0           e      6
30  0  1  1  0  0           e      6
31  0  1  1  0  0           e      6
32  0  1  1  0  0           e      6
33  0  1  1  0  0           e      6
34  0  1  1  0  0           e      6
35  1  1  0  0  0           r      7
36  1  1  0  0  0           r      7
37  1  1  0  0  0           r      7
38  1  1  0  0  0           r      7
39  0  0  0  1  0           w      8
40  0  0  0  1  0           w      8
41  0  0  0  1  0           w      8
42  0  0  0  1  0           w      8
43  0  0  1  0  0           k      9
44  0  0  1  0  0           g      9
45  0  0  1  0  0           g      9
46  1  0  0  0  0           g      9
47  0  0  1  0  0           d     10
48  0  0  1  0  0           d     10
49  0  0  1  0  0           d     10
50  0  0  1  0  0           d     10
51  1  1  0  0  0           r     11
52  1  1  0  0  0           t     11
53  0  0  1  1  0           l     11
54  2  1  0  0  1           e     11
55  0  1  0  1  0           t     11
56  1  0  0  1  0           d     11
57  0  2  0  0  0           d     11

In [400]:
data_df.label.value_counts()

5     8
3     8
11    7
6     6
4     5
1     5
10    4
9     4
8     4
7     4
2     3
Name: label, dtype: int64